steps:
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/impactapi:latest", "."]
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/impactapi:latest"]
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "run",
        "deploy",
        "impact-api",
        "--image",
        "gcr.io/$PROJECT_ID/impactapi:latest",
        "--region",
        "europe-north1",
        "--platform",
        "managed",
        "--allow-unauthenticated",
      ]
  - id: "apply migrations"
    name: "gcr.io/google-appengine/exec-wrapper"
    args:
      [
        "-i",
        "gcr.io/$PROJECT_ID/impactapi",
        "-s",
        "${PROJECT_ID}:${_REGION}:${_INSTANCE_NAME}",
        "-e",
        "SETTINGS_NAME=${_SECRET_SETTINGS_NAME}",
        "-e",
        "CLOUD_SQL_CONNECTION_NAME=${PROJECT_ID}:${_REGION}:${_INSTANCE_NAME}",
        "-e",
        "DB_NAME=$_DB_NAME",
        "-e",
        "DB_USER=$_DB_USER",
        "-e",
        "DB_PASS=$_DB_PASSWORD",
        "--",
        "python",
        "manage.py",
        "migrate",
      ]

  - id: "collect static"
    name: "gcr.io/google-appengine/exec-wrapper"
    args:
      [
        "-i",
        "gcr.io/$PROJECT_ID/impactapi",
        "-s",
        "${PROJECT_ID}:${_REGION}:${_INSTANCE_NAME}",
        "-e",
        "SETTINGS_NAME=${_SECRET_SETTINGS_NAME}",
        "-e",
        "CLOUD_SQL_CONNECTION_NAME=${PROJECT_ID}:${_REGION}:${_INSTANCE_NAME}",
        "-e",
        "DB_NAME=$_DB_NAME",
        "-e",
        "DB_USER=$_DB_USER",
        "-e",
        "DB_PASS=$_DB_PASSWORD",
        "--",
        "python",
        "manage.py",
        "collectstatic",
        "--verbosity",
        "2",
        "--no-input",
      ]

substitutions:
  _INSTANCE_NAME: effekt-db
  _REGION: europe-north1
  _SERVICE_NAME: impact-api
  _SECRET_SETTINGS_NAME: django_settings
  _DB_NAME: ${sm://projects/$PROJECT_ID/secrets/impact_api_db_name/versions/latest}
  _DB_USER: ${sm://projects/$PROJECT_ID/secrets/impact_api_db_username/versions/latest}
  _DB_PASSWORD: ${sm://projects/$PROJECT_ID/secrets/impact_api_db_password/versions/latest}

images: ["gcr.io/$PROJECT_ID/impactapi:latest"]