steps:
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/impactapi:latest", "."]
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/impactapi:latest"]
  - id: "apply migrations"
    name: "gcr.io/google-appengine/exec-wrapper"
    args:
      [
        "-i",
        "gcr.io/$PROJECT_ID/${_SERVICE_NAME}",
        "-s",
        "${PROJECT_ID}:${_REGION}:${_INSTANCE_NAME}",
        "-e",
        "SETTINGS_NAME=${_SECRET_SETTINGS_NAME}",
        "--",
        "python",
        "manage.py",
        "migrate",
      ]
  - name: "gcr.io/cloud-builders/gcloud"
    id: "deploy"
    waitFor: ["apply migrations"]
    args:
      [
        "run",
        "deploy",
        "impact-api",
        "--image",
        "gcr.io/$PROJECT_ID/impactapi:latest",
        "--region",
        "europe-north1",
        "--platform",
        "managed",
        "--allow-unauthenticated",
      ]

  - id: "collect static"
    waitFor: ["deploy"]
    name: "gcr.io/google-appengine/exec-wrapper"
    args:
      [
        "-i",
        "gcr.io/$PROJECT_ID/${_SERVICE_NAME}",
        "-s",
        "${PROJECT_ID}:${_REGION}:${_INSTANCE_NAME}",
        "-e",
        "SETTINGS_NAME=${_SECRET_SETTINGS_NAME}",
        "--",
        "python",
        "manage.py",
        "collectstatic",
        "--verbosity",
        "2",
        "--no-input",
      ]

substitutions:
  _INSTANCE_NAME: django-instance
  _REGION: europe-north1
  _SERVICE_NAME: impact-api
  _SECRET_SETTINGS_NAME: django_settings

images: ["gcr.io/$PROJECT_ID/impactapi:latest"]
