steps:
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/impactapi:latest", "."]
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/impactapi:latest"]
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "run",
        "deploy",
        "impact-api",
        "--image",
        "gcr.io/$PROJECT_ID/impactapi:latest",
        "--region",
        "europe-north1",
        "--platform",
        "managed",
        "--allow-unauthenticated",
      ]
  - id: "apply migrations"
    name: "gcr.io/google-appengine/exec-wrapper"
    args:
      [
        "-i",
        "gcr.io/$PROJECT_ID/impactapi",
        "-s",
        "${PROJECT_ID}:${_REGION}:${_INSTANCE_NAME}",
        "-e",
        "SETTINGS_NAME=${_SECRET_SETTINGS_NAME}",
        "-e",
        "CLOUD_SQL_CONNECTION_NAME=${PROJECT_ID}:${_REGION}:${_INSTANCE_NAME}",
        "-- --DB_PASS=$$DB_PASS --DB_USER=$$DB_USER --DB_NAME=$$DB_NAME",
        "--",
        "python",
        "manage.py",
        "migrate",
      ]
    secretEnv: ['DB_NAME', 'DB_USER', 'DB_PASS']
  - id: "collect static"
    name: "gcr.io/google-appengine/exec-wrapper"
    args:
      [
        "-i",
        "gcr.io/$PROJECT_ID/impactapi",
        "-s",
        "${PROJECT_ID}:${_REGION}:${_INSTANCE_NAME}",
        "-e",
        "SETTINGS_NAME=${_SECRET_SETTINGS_NAME}",
        "-- --DB_PASS=$$DB_PASS --DB_USER=$$DB_USER --DB_NAME=$$DB_NAME",
        "--",
        "python",
        "manage.py",
        "collectstatic",
        "--verbosity",
        "2",
        "--no-input",
      ]
    secretEnv: ['DB_NAME', 'DB_USER', 'DB_PASS']

substitutions:
  _INSTANCE_NAME: effekt-db
  _REGION: europe-north1
  _SERVICE_NAME: impact-api
  _SECRET_SETTINGS_NAME: django_settings

availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/impact_api_db_name/versions/latest
      env: 'DB_NAME'
    - versionName: projects/$PROJECT_ID/secrets/impact_api_db_username/versions/latest
      env: 'DB_USER'
    - versionName: projects/$PROJECT_ID/secrets/impact_api_db_password/versions/latest
      env: 'DB_PASS'

images: ["gcr.io/$PROJECT_ID/impactapi:latest"]