# Generated by Django 4.0.4 on 2022-04-29 16:45

import api.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charity_abbreviation', models.CharField(max_length=10)),
                ('charity_name', models.CharField(max_length=200)),
                ('start_year', models.IntegerField(validators=[api.models.validate_year])),
                ('start_month', models.IntegerField(validators=[api.models.validate_month])),
                ('short_output_description', models.CharField(max_length=100)),
                ('long_output_description', models.CharField(max_length=1000)),
                ('cents_per_output', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MaxImpactDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_year', models.IntegerField(validators=[api.models.validate_year])),
                ('start_month', models.IntegerField(validators=[api.models.validate_month])),
            ],
        ),
        migrations.CreateModel(
            name='Grant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charity_name', models.CharField(max_length=200)),
                ('charity_abbreviation', models.CharField(blank=True, max_length=10, null=True)),
                ('short_output_description', models.CharField(max_length=100)),
                ('long_output_description', models.CharField(max_length=1000)),
                ('grant_in_cents', models.IntegerField()),
                ('number_outputs_purchased', models.IntegerField()),
                ('max_impact_distribution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.maximpactdistribution')),
            ],
        ),
    ]
