# Generated by Django 4.0.4 on 2022-04-29 09:09

import api.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MaxImpactDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charity_name', models.CharField(max_length=200)),
                ('start_year', models.IntegerField(validators=[api.models.validate_year])),
                ('start_month', models.IntegerField(validators=[api.models.validate_month])),
                ('end_year', models.IntegerField(blank=True, null=True, validators=[api.models.validate_year])),
                ('end_month', models.IntegerField(blank=True, null=True, validators=[api.models.validate_month])),
                ('cents_per_output', models.IntegerField()),
                ('output_type', models.CharField(max_length=511)),
                ('cents_donated', models.IntegerField(default=100)),
                ('max_impact_distribution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.maximpactdistribution')),
            ],
        ),
    ]
