# Generated by Django 4.0.4 on 2022-05-25 16:07

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_intervention_long_description_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allotment',
            name='number_outputs_purchased',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='allotment',
            name='sum_in_cents',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='cents_per_output',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='start_month',
            field=models.PositiveIntegerField(validators=[api.models.validate_month]),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='start_year',
            field=models.PositiveIntegerField(validators=[api.models.validate_year]),
        ),
        migrations.AlterField(
            model_name='maximpactfundgrant',
            name='start_month',
            field=models.PositiveIntegerField(validators=[api.models.validate_month]),
        ),
        migrations.AlterField(
            model_name='maximpactfundgrant',
            name='start_year',
            field=models.PositiveIntegerField(validators=[api.models.validate_year]),
        ),
    ]
