# Generated by Django 4.2.6 on 2023-11-06 17:52

import api.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_evaluation_cents_per_output_lower_bound_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllGrantsFundGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_year', models.PositiveIntegerField(validators=[api.models.validate_year])),
                ('start_month', models.PositiveIntegerField(validators=[api.models.validate_month])),
            ],
        ),
        migrations.AlterField(
            model_name='allotment',
            name='max_impact_fund_grant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.maximpactfundgrant'),
        ),
        migrations.AddConstraint(
            model_name='allgrantsfundgrant',
            constraint=models.UniqueConstraint(fields=('start_year', 'start_month'), name='unique_date_agf'),
        ),
        migrations.AddField(
            model_name='allotment',
            name='all_grants_fund_grant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.allgrantsfundgrant'),
        ),
    ]
