# Generated by Django 4.2.6 on 2023-11-08 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_allgrantsfundgrant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='allotment',
            name='comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='allotment',
            name='number_outputs_purchased_lower_bound',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='allotment',
            name='number_outputs_purchased_upper_bound',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='allotment',
            name='source_name',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='allotment',
            name='source_url',
            field=models.TextField(blank=True),
        ),
    ]
